### ISSUE TITLE
自动化时代 是不是缺点什么呢？

### ISSUE THREAD

**Issue by marklove5102** [xizon/F-Curator#2]
比如自动识别复制内容填充
和（插件）浏览器互动 用于方便快捷收集url

**Comment by xizon** [comment]
OK感谢建议，目前满足了日常的URL保存需求就暂时还没有更新。抽空做一些改良，最近工作忙没有更新太多开源软件 ：）

**Comment by marklove5102** [comment]
好的加油哦！
